description: >
  Select your go version or any of the available tags here: https://hub.docker.com/r/cimg/go/tags
docker:
  - image: 'cimg/go:<<parameters.tag>>'
parameters:
  tag:
    default: '1.25'
    description: >
      Pick a specific circleci/go image variant:
      https://hub.docker.com/r/cimg/go/tags
    type: string
